-- Migration: Ajouter la colonne 'clauses' au retour de get_public_quote
-- À exécuter dans Supabase SQL Editor
--
-- DIAGNOSTIC: D'abord vérifier si 'clauses' est déjà dans le SELECT
-- Exécuter cette requête pour voir la définition actuelle :
--
--   SELECT prosrc FROM pg_proc WHERE proname = 'get_public_quote';
--
-- Si 'clauses' n'apparaît PAS dans le SELECT de submissions, appliquer le fix ci-dessous.
--
-- Le fix consiste à recréer la fonction avec 'clauses' ajouté au SELECT.
-- Copier la définition retournée par pg_proc, ajouter s.clauses dans le SELECT,
-- et exécuter CREATE OR REPLACE FUNCTION.
--
-- Exemple de modification (adapter selon la définition réelle) :
--
--   Dans le SELECT qui lit submissions, ajouter :
--     s.clauses
--
--   Exemple avant :
--     SELECT s.id, s.title, s.status, s.current_version, ...
--
--   Exemple après :
--     SELECT s.id, s.title, s.status, s.current_version, s.clauses, ...
--
-- NOTE: La colonne 'clauses' (JSONB) existe déjà sur la table submissions.
-- Elle contient un tableau de clauses contractuelles [{title, content, title_en, content_en}].
-- quote.html la lit via: var clauses = sub.clauses || [];
